logging:
  level:
    org:
      springframework: ERROR
spring:
  datasource:
    password: ddk0Re!!wIjpGAPzfa.XrQ
    platform: postgres
    url: jdbc:postgresql://localhost:5432/le_tech
    username: le_tech
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-source: metadata
              create-target: ./src/main/resources/db/migration/create.sql
  main:
    banner-mode: 'off'
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: eb7dcb44c7f08deaf8ef
            clientSecret: 494afbbf5501379c3880ab0ab86443668c3ecfc2
            scope:
              - user:email
              - read:user
